name: iranicard_mobile_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 4.0.0+4066-w

environment:
  sdk: ">=3.10.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  authorization_module:
    path: ../../authorization-module/src

    #git:
    #  url: https://git.plzdev.ir/mobile/authorization-module.git
    #  path: src # The relative path to the repository root. (lib is default - here we have src)
    #  ref: develop # The branch to checkout on the repository. (main is default)
  iranexchange:
    path: ../../iranexchange/src
    #git:
    #   url: https://git.plzdev.ir/mobile/iranexchange.git
    # path: src # The relative path to the repository root. (lib is default - here we have src)
    # ref: develop # The branch to checkout on the repository. (main is default)
    # pateh:
    #   # path: ../../pateh-mobile-app/src
    # git:
    #   url: git@git.plzdev.ir:paliz/pateh-mobile-app.git
    #   path: src # The relative path to the repository root. (lib is default - here we have src)
    #   ref: develop # The branch to checkout on the repository. (main is default)

  get: ^4.7.3
  shared_preferences: ^2.2.3
  http: ^1.2.2
  persian_number_utility: ^1.1.4
  webview_flutter: ^4.9.0
  carousel_slider: ^5.0.0
  extended_image: ^10.0.1
  easy_debounce: ^2.0.3
  modal_bottom_sheet: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_chat_ui: ^1.6.15
  file_picker: ^10.2.0
  infinite_scroll_pagination: ^4.0.0
  shamsi_date: ^1.0.4
  qr_flutter: ^4.1.0
  # firebase_analytics: ^11.5.0
  # firebase_core: ^3.14.0
  # firebase_messaging: ^15.2.5
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  flutter_widget_from_html: ^0.17.1
  shimmer: ^3.0.0
  share_plus: ^12.0.0
  yaml: ^3.1.2
  http_parser: ^4.0.2
  app_settings: ^5.1.1
  intl: ^0.20.2
  app_links: ^7.0.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^17.0.0
  device_info_plus: ^11.1.0
  base32: ^2.1.3
  mobile_scanner: ^7.0.1
  flutter_inappwebview: ^6.1.5
  flutter_dotenv: ^5.2.1
  web: ^1.1.1
  logger: ^2.6.0
  dual_custom_date_picker: ^1.3.1
  connectivity_plus: ^6.1.4
  supabase_flutter: ^2.12.0
  clarity_flutter: ^1.9.0
  share_handler: ^0.0.25

dependency_overrides:
  app_links: ^7.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon/appicon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/launcher_icon/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/launcher_icon/ic_launcher_foreground.png"
  image_path_ios: "assets/launcher_icon/appicon.png"
  web:
    generate: true
    image_path: "assets/launcher_icon/appicon.png"
    background_color: "#ffffff"

flutter-assets:
  auto-generate: true
  assets-path: assets
  output-path: lib/res
  ignore-ext: false


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/KFOmCnqEu92Fr1Me4GZLCzYlKw.woff2

  assets:
    - irc.env
    - irx.env
    - assets/images/
    - assets/images/svgs/
    - assets/images/svgs/banks/
    - assets/images/svgs/sessions/
    - assets/animations/
    - assets/super_app/
    - assets/super_app/svgs/
    - pubspec.yaml
    - android/app/build.gradle
    - assets/fonts/Estedad.ttf
    - assets/fonts/Flutter-Iconsax.ttf
    # - assets/fonts/icons/Pateh.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
